### ISSUE TITLE
What's the "Identity" and the "Token Provider URL" to login the demo?

### ISSUE THREAD

**Issue by flyingxu** [twilio/TwilioChatXamarinBindings#11]
When I run the demo app, "Identity" and "Token Provider URL" are needed to login.

For Identity, is it my twilio "Account Sid" or my Chat Service SID (I created a chat service in Twilio Console)?

**Comment by berkus** [comment]
No,

you as a developer should provide users with login infrastructure, using Twilio building blocks.

"Identity" is the name of your user in your service, you define what it is - an unique id, email, or something else.

Token Provider is the service you wrote to authenticate that user, validating that "Identity" is actually why they claim they are. If authentication is successful, your Token Provider should produce a twilio token used for accessing the chat service. If authentication fails, your Token Provider should indicate the error to the user somehow, it's up to you how to do it.

See [Access Tokens](https://www.twilio.com/docs/iam/access-tokens) in Twilio documentation for more details.

**Comment by berkus** [comment]
Closing as there's no further activity. Reopen if you have other questions regarding Identity.
