### ISSUE TITLE
access manager and token refresh

### ISSUE THREAD

**Issue by bryanvam** [twilio/TwilioChatXamarinBindings#13]
how is token refreshing handled?

**Comment by aleksandrsivanovs** [comment]
Hi!

Currently through AccessManager which will tell you with help of events/callbacks that token is about t expire. This functionality (notifying you about token expiration with events/callbacks) will move to the Twilio Chat library itself in the next release, which will be released soon. 

Aleksandrs

**Comment by bryanvam** [comment]
thanks for the quick reply. i was more meaning in the context of this project. i dont see anything referencing the AccessManager. will this project be updated when the chat library gets updated?

**Comment by aleksandrsivanovs** [comment]
Yes, it's on my to do list after mentioned twilio chat library release

**Comment by aleksandrsivanovs** [comment]
we have just released v0.4.0 which drops need for access manager: https://www.nuget.org/packages/Twilio.Chat.Xamarin/
