### ISSUE TITLE
Message not received on Android client side

### ISSUE THREAD

**Issue by KKS91** [twilio/TwilioChatXamarinBindings#18]
I've created the android client and sent the message which is received at the Chat Service side but message sent by chat service has not been received on the Android side. It works fine with web client.

I've subscribed to ChatClient.NewMessageNotification API also added handler for Channel.MessageAdded but it is not getting executed.
When I send the message Channel.MessageAdded() gets executed but when when message get added to the channel from the server side then none of these handler is getting executed.

Note: I've not subscribed to FCM . I would like to know if FCM is the only way to receive the message from the server? OR we can get it through regular channel as well.

**Comment by berkus** [comment]
To receive MessageAdded notification you must be online and have a fully synchronized ChatClient.

FCM/APNS is only needed to receive push notifications.
