### ISSUE TITLE
iOS - Native linking error. Framework not found TwilioChatClient

### ISSUE THREAD

**Issue by whitewolf33** [twilio/TwilioChatXamarinBindings#2]
Hi,

I downloaded the zip folder and tried to build the solution (with iOS as the startup) but I am experiencing the "

> framework not found TwilioChatClient

" Issue. Would be good to have the sample solution ready to build without having to fix the native linking issues.

_Have not tried the Android yet but will let you know once I have tried it._

Have uploaded the file which describes the errors while trying to run the ChatDemo.iOS as the startup project.

![screen shot 2018-01-27 at 2 12 14 am](https://user-images.githubusercontent.com/4328043/35599420-cd37d0c2-067c-11e8-85ae-f77fd93d8a76.png)

Please let me know if you need any further information on this.

**Comment by aleksandrsivanovs** [comment]
Hi!

have you built the actul bindings beforehand?

in the readme there is section 
```
cd Twilio.Chat
./nugetBuildAndPack.sh
cd -
```

this script will fetch the dependencies and do the building of bindings. 
after that you can build the sample project.

also, the built bindings are already available on the nuget.org: https://www.nuget.org/packages/Twilio.Chat.Xamarin/

**Comment by whitewolf33** [comment]
Hi Aleksandr;

I did not build the bindings earlier. Will try that soon.

Regarding Nuget: 
Droid - I could install the nuget package successfully for android project. Have not run it yet.

iOS - Gives an error while trying to add the package...

> Could not install package 'Twilio.Chat.Xamarin 0.1.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is this just an Android specific nuget? 

Could not see any other nuget package from the Author in nuget
https://www.nuget.org/profiles/rtd-sdk-xamarin

Please let me know.

**Comment by aleksandrsivanovs** [comment]
it's both Android and iOS binding. I will check the version (and this nuget is published by us, build from source in this repo)

**Comment by aleksandrsivanovs** [comment]
there is a problem indeed. 
I'm trying to fix it - new version will be released to nuget.org hopefully today. 
thanks for the report! (somehow, completely missed it)

**Comment by aleksandrsivanovs** [comment]
new version is published in nuget.org, v0.1.1
I've verified it to be working (with local nuget repo publish / consume).

currently it's in review form nuget.org, will post here the update when it will be available

**Comment by whitewolf33** [comment]
Sounds good. Please do post a message when the latest is available in nuget. Keen to try it out. Thanks for the quick turn around.

**Comment by aleksandrsivanovs** [comment]
now verified by nuget.org, v0.1.1 is here: https://www.nuget.org/packages/Twilio.Chat.Xamarin/0.1.1

please close the issue if the install was successful.

**Comment by whitewolf33** [comment]
Will do. Thanks.

**Comment by whitewolf33** [comment]
Got the nuget packages to install in ChatDemo sample iOS project from github but unable to build the iOS project.

Have tried restarting VS Mac 
Have downgraded XF to 2.4 
Completely cleared the bin and obj 
Unloaded all Droid and Native binding projects

But no luck. Since it is third party lib I do not get to see the method causing the issue. 

Have not tried building the ChatDemo solution. Does the below error ring a bell to you?

> /github/TwilioChatXamarinBindings/Sample/ChatDemo.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Void ObjCRuntime.BlockLiteral::SetupBlockUnsafe(System.Delegate,System.Delegate)', referenced from the method 'System.Void Twilio.Chat.iOS.TwilioChatClient::ChatClientWithToken(System.String,Twilio.Chat.iOS.TwilioChatClientProperties,Twilio.Chat.iOS.TwilioChatClientDelegate,Twilio.Chat.iOS.TwilioClientCompletion)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. (MT2101) (ChatDemo.iOS)

**Comment by aleksandrsivanovs** [comment]
just tried to rebuild the ChatDemo sample iOS project and run on simulator (with both locally built binding and installed from nuget.org) - all works fine. 
please try out ChatDemo sample :)

will try to find out what's the problem with mentioned error.

**Comment by whitewolf33** [comment]
OK. Got it to work. Setting the SDK Version to 11.2 (explicitly) and/ or setting the Linker to Do not link ( I think I changed this previously trying to make things work), did the trick.

Can you please help me with the Identity : Is this the Chat ServiceID or the Twilio AccountSID?
Also, the Token provider URL? Where should I look for this? 

Please excuse my limited knowledge with Twilio. Had the REST API working well by just providing the SID and the REST API resource to connect to, but this, I do not have a clue. Am going to try few different things, anyway, until you respond :)

Thanks.

**Comment by aleksandrsivanovs** [comment]
there is small section in readme in regards to setup the token provider for sample app:
https://github.com/twilio/TwilioChatXamarinBindings#common

identity will be baked into the twilio access token (more info on access tokens can be found here: 
https://www.twilio.com/docs/api/rest/access-tokens)

the sample JS code for Twilio Runtime which I've used in the sample app is also available on github gists here: https://gist.github.com/aleksandrsivanovs/abd04d4c139941467ff6b5fa102821e4

the gist and docs should give you the common understanding of how to create token and how to create it.

**Comment by whitewolf33** [comment]
Read through the Read Me again and.. got to know about the Twilio Runtime Function. Will give it a shot. Thanks for your prompt response.

Closing this issue now.

**Comment by mayurbhavsar45** [comment]
Guys its working well with nuget package
https://www.nuget.org/packages/Twilio.Chat.Xamarin/
