### ISSUE TITLE
Getting 401 Authorized 

### ISSUE THREAD

**Issue by sylendra7** [twilio/TwilioChatXamarinBindings#20]
[2019-09-15 00:04:02.062] [INFO] [TokenProvider] Got chat token: {"identity":"1","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJpc3MiOiJTSzczN2U1NzMyZjg1Mjc2OWUxNDhlNDc4OWE5MzllNGFlIiwiZXhwIjoxNTY4NDg5NjQzLCJqdGkiOiJTSzczN2U1NzMyZjg1Mjc2OWUxNDhlNDc4OWE5MzllNGFlLTE1Njg0ODYwNDMiLCJzdWIiOiJBQzg3MWFhNmJjMGJkMjdlYTY0M2Q3MzczNDNkMmFiYjg2IiwiZ3JhbnRzIjp7ImlkZW50aXR5IjoiMSIsInZpZGVvIjp7fSwiY2hhdCI6eyJzZXJ2aWNlX3NpZCI6IklTNzk3ZDQwMGQyZGYxNGE5YmEwM2VjMjJmMzlhN2NjNmMiLCJwdXNoX2NyZWRlbnRpYWxfc2lkIjoiQ1IwYzA5NzBhNjY4ZTkwNTc4NDk0ZTZhZDdmNjc3MmJiMCJ9LCJkYXRhX3N5bmMiOnsic2VydmljZV9zaWQiOiJkZWZhdWx0In19fQ.dMPIVIqFEaaS7a1vEIFpwa-MUweT6e1a4Q5jPsqQwp4"}
Resolved pending breakpoint at 'ChatClientCallbackListener.cs:21,1' to void KBB.Droid.ChatClientCallbackListener.OnSuccess (Com.Twilio.Chat.ChatClient result) [0x00000].
Resolved pending breakpoint at 'ChatClientCallbackListener.cs:53,1' to void KBB.Droid.ChatClientCallbackListener.ChannelSynchronizationChanged (object sender, Com.Twilio.Chat.SynchronizationChangedEventArgs args) [0x00001].
[ChatClient] Twilio Chat SDK version 4.2.0-26d8eca
[TWC]         -936375952 |      1 | ThreadedExecutor.Impl | Creating 16 threads in the executor pool
[TWC]         -989251216 |      4 | Twilsock.Client | client: version: , build id: 13616, build branch: , os: android, arch: armeabi-v7a
[TWC]         -964175504 |      6 | State.Disconnected | Leaving state: Disconnected
[TWC]         -964175504 |      4 | Twilsock.Client | Changing state: Disconnected --> Transport connecting
[TWC]         -964175504 |      9 | State.TransportConnecting | Entering state: Transport connecting
[TWC]         -989251216 |      7 | RawHttp | client: version: , build id: 13616, build branch: , os: android, arch: armeabi-v7a
[TWC]         -989251216 |     11 | NotificationClient | Constructed
[TWC]         -989251216 | IPM | client: version: , build id: 7092, build branch: , os: android, arch: armeabi-v7a, chat lib: , datasync lib: 
[TWC]         -989251216 |     13 | SyncClient | initializing sdk: cpp/ os: Linux/4.4.111-16139119 platform: armv8l/
[TWC]         -989251216 |     13 | SyncClient | build #5444 release:  branch: 
[TWC]         -989251216 |     14 | TSSubscriptions | constructed
[TWC]         -989251216 |     15 | TSNotificationRouter | constructed
[TWC]         -989251216 |     16 | TSCoreDataService | constructed
[TWC]         -989251216 |     15 | TSNotificationRouter | Registering for notification events
[TWC]         -989251216 | IPM | [0e4X1] client: StateNoState->StateNotInitialized
[TWC]         -989251216 | IPM | [0e4X1] client: StateNotInitialized->StateInitializing
[TWC]         -989251216 | IPM | session: start initialization
[TWC]         -989251216 | IPM | [listener] on client sync 0
[TWC]         -989251216 | IPM | [D378H] session: StateNoState->StateNotInitialized
[TWC]         -989251216 | IPM | [D378H] session: StateNotInitialized->StateInitializing
[TWC]         -989251216 |     17 | SyncList | constructed
[TWC]         -989251216 |     19 | TSCollectionCreateActivity | constructed
[TWC]         -989251216 |     19 | TSCollectionCreateActivity | start 1
[TWC]         -989251216 |     17 | SyncList | create action id: 1 name: [nullopt] purpose: com.twilio.rtd.ipmsg
[TWC]         -979887760 |     19 | TSCollectionCreateActivity | query [0] /v3/Lists
[TWC]         -968894096 |     15 | TSNotificationRouter | Transport state changed. Is enabled: 0
[TWC]         -968894096 |     15 | TSNotificationRouter | Successfully subscribed for notification message type: com.twilio.rtd.cds.document
[TWC]         -968894096 |     15 | TSNotificationRouter | Successfully subscribed for notification message type: com.twilio.rtd.cds.list
[TWC]         -968894096 |     15 | TSNotificationRouter | Successfully subscribed for notification message type: com.twilio.rtd.cds.map
[TWC]         -968894096 |     15 | TSNotificationRouter | Successfully subscribed for notification message type: twilio.sync.event
[TWC]         -968894096 |     11 | NotificationClient | onTwilsockDisconnected: Unknown reason
[TWC]         -968894096 |     11 | NotificationClient | updateAggregatedTransportState, old state: 2, new state 2
[TWC]         -968894096 |     11 | NotificationClient | onRegStateChanged: twilsock: 'internal twilsock address', state: Registering
[TWC]         -981968528 |      8 | Websocket | Connected
[TWC]         -964175504 |      5 | Twilsock.ClientImpl | Twilsock Tweaks: null
[TWC]         -964175504 |      5 | Twilsock.ClientImpl | sendInit, id = RQ144065a67be342cc8cf92e4b01ae9b20
[TWC]         -964175504 |      9 | State.TransportConnecting | Leaving state: Transport connecting
[TWC]         -964175504 |      4 | Twilsock.Client | Changing state: Transport connecting --> Initialising
[TWC]         -964175504 |     30 | State.Initialising | Entering state: Initialising
[TWC]         -968894096 |      4 | Twilsock.Client | Reply status for init request is failure: {"code":401,"status":"UNAUTHORIZED"}
[TWC]         -986130064 |      4 | Twilsock.Client | Server has just initiated process of closing connection! 401: UNAUTHORIZED
[TWC]         -968894096 |     30 | State.Initialising | Leaving state: Initialising
[TWC]         -968894096 |      4 | Twilsock.Client | Changing state: Initialising --> TransportDisconnecting
[TWC]         -968894096 |     32 | State.TransportDisconnecting | Entering state: TransportDisconnecting
[TWC]         -983008912 |     11 | NotificationClient | onTwilsockFatalError: 14 - UNAUTHORIZED
[TWC]         -983008912 |     11 | NotificationClient | updateAggregatedTransportState, old state: 2, new state 2
[TWC]         -968894096 |     32 | State.TransportDisconnecting | Success reply can not be sent. Twilsock is not in connected state
[TWC]         -968894096 |     32 | State.TransportDisconnecting | Disconnect process has already been started
[TWC]         -964175504 |      8 | Websocket | Disconnected
[TWC]         -980928144 |     32 | State.TransportDisconnecting | Leaving state: TransportDisconnecting
[TWC]         -980928144 |      4 | Twilsock.Client | Changing state: TransportDisconnecting --> Disconnected
[TWC]         -980928144 |     34 | State.Disconnected | Entering state: Disconnected
[TWC]         -979887760 |     11 | NotificationClient | onTwilsockDisconnected: Unknown reason
[TWC]         -979887760 |     11 | NotificationClient | updateAggregatedTransportState, old state: 2, new state 2

**Comment by berkus** [comment]
Hi

This error is usually returned when token is invalid, in your case it's probably because you have too many grants enabled in the token, could you please re-capture logs in the TRACE log level as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md) and post the log file with unsuccessfuly session?

**Comment by sylendra7** [comment]
Thanks @berkus  sent an invalid token .
