### ISSUE TITLE
IOS Build Error Lanching In Physical device 12.4version 

### ISSUE THREAD

**Issue by PRAVEENPOTLA** [twilio/TwilioChatXamarinBindings#22]
Can't resolve the reference 'Foundation.NSArray Foundation.NSArray::FromNSObjects(!!0[])', referenced from the method 'System.Void ObjCRuntime.Trampolines/NIDMessagesCompletion::Invoke(Twilio.Chat.iOS.Result,Twilio.Chat.iOS.Message[])' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. ChatDemo.iOS

**Comment by PRAVEENPOTLA** [comment]
Please Help me Anyone Knows

**Comment by berkus** [comment]
Perhaps related to https://github.com/twilio/TwilioChatXamarinBindings/issues/21#issuecomment-533068760

**Comment by PRAVEENPOTLA** [comment]
Hi berkus,

We are Using Xcode Version 10.3
Target Device Version 12.4 
Xamarin version :  4.12.3
Xamarin.ios version and xamarin Mac SDK : 12.4.0.64

**Comment by PRAVEENPOTLA** [comment]
@Berkus If possible please reply me fast because it's very urgent for me.

**Comment by PRAVEENPOTLA** [comment]
Help me fast it urgent for me

**Comment by PRAVEENPOTLA** [comment]
Hi  Berkus,

Please help me  Regarding IOS Bulid Error

**Comment by berkus** [comment]
Hi

We have tested the issue and it is fixed if you update to the latest versions indicated below; don't forget to restart your Visual Studio so that all updates are applied.

```
=== Visual Studio Community 2019 for Mac ===

Version 8.3 (build 1805)
Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

=== Mono Framework MDK ===

Runtime:
    Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
    Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK Versions:
    3.0.100
    2.1.701

=== .NET Core Runtime ===

Runtime Versions:
    3.0.0
    2.1.12

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Version: 6.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400
```

**Comment by PRAVEENPOTLA** [comment]
Hi Berkus,
 Xcode version 11.0 is mandatory. right now we have Xcode 10.3 only

**Comment by PRAVEENPOTLA** [comment]
Hi Berkus,

Thanks for supporting me. It's working fine right now Thank you so much

**Comment by PRAVEENPOTLA** [comment]
Hi Berkus, 
  how to know member is in online or offline and also sent message read or not

**Comment by PRAVEENPOTLA** [comment]
Hi Berkus,
     In iOS, the message Added method is not firing. when we chat in the channel

**Comment by PRAVEENPOTLA** [comment]
Please help me Ios message added not firing

**Comment by berkus** [comment]
@PRAVEENPOTLA great that it worked!

Do you have logs for the case when messageAdded is not firing?

**Comment by berkus** [comment]
I will close this one, please open a new ticket for the messageAdded case, and add logs if you can.
