### ISSUE TITLE
How to get unread message count 

### ISSUE THREAD

**Issue by PRAVEENPOTLA** [twilio/TwilioChatXamarinBindings#26]
In uncounsumed message Index method always returning zero in andriod. Did not check in iOS

**Comment by rusmonster** [comment]
Chat does not automatically set the Consumption Horizon. If you do not explicitly set this within your application, no Consumption Horizon will exist for a User within the Channel. Without a Consumption Horizon, your user's Consumption Horizon (read status) will not synchronize correctly across clients. If a user does not have a Consumption Horizon set on a channel, getting unconsumed messages will always return 0. If a member of a Channel has no consumption status, their last consumed index and timestamp will be null or 0 depending on the platform.

see the [Guide](https://www.twilio.com/docs/chat/consumption-horizon#consumption-horizon) for details

**Comment by PRAVEENPOTLA** [comment]
Thanks
