### ISSUE TITLE
Unable to establish connection to Twilio Sync service

### ISSUE THREAD

**Issue by AlfonChitoSalano** [twilio/TwilioChatXamarinBindings#29]
**Description**
When I run the xamarin android application from the sample I get the following error Error 0:1401 Unable to establish connection to Twilio Sync service

**Expected Behavior**
should go to ChatClientCallbackListener OnSuccess method

**Actual Behavior**
throws an error "Error 0:1401 Unable to establish connection to Twilio Sync service"

**Reproduces how Often**
every time

**Android API**
28

**Android Device**
Samsung A10 emulator/Samsung Tablet real device
[logs.txt](https://github.com/twilio/TwilioChatXamarinBindings/files/4422249/logs.txt)

**Comment by berkus** [comment]
Hi!

This is clearly a problem with your token:

{"method":"close","status":{"code":401,"status":"UNAUTHORIZED","description":"Invalid Access Token","errorCode":20101}}

I see an invalid push_credential_sid in the token:
```
  "grants": {
    "ip_messaging": { <-- this is very obsolete, use "chat"
      "endpoint_id": "TonestroSupportChat:christian.kapplmueller@tonestro.com:undefined", <-- this is very obsolete, token should not contain endpoint_id
      "push_credential_sid": "kkk" <-- this is an invalid push credential SID
    }
  },
```

Also, it attempts to connect to Chat service instance `IS6c393145995b49f68f14ad5eae80ed1f` which does **not** exist under your account.

I have not checked the validity of token signing key - fix the above problems first.

**Comment by AlfonChitoSalano** [comment]
> Hi!
> 
> This is clearly a problem with your token:
> 
> {"method":"close","status":{"code":401,"status":"UNAUTHORIZED","description":"Invalid Access Token","errorCode":20101}}
> 
> I see an invalid push_credential_sid in the token:
> 
> ```
>   "grants": {
>     "ip_messaging": { <-- this is very obsolete, use "chat"
>       "endpoint_id": "TonestroSupportChat:christian.kapplmueller@tonestro.com:undefined", <-- this is very obsolete, token should not contain endpoint_id
>       "push_credential_sid": "kkk" <-- this is an invalid push credential SID
>     }
>   },
> ```
> 
> Also, it attempts to connect to Chat service instance `IS6c393145995b49f68f14ad5eae80ed1f` which does **not** exist under your account.
> 
> I have not checked the validity of token signing key - fix the above problems first.

Please ignore this Chat service instance "IS6c393145995b49f68f14ad5eae80ed1f" because I intentionally delete it for security purpose yesterday. I will just recreate a new one.

Anyway, from your analysis that the grant from token is absolute, is it because of the programmable chat android lib as you could see in this nuget is obsolete already "https://www.nuget.org/packages/Twilio.Chat.Xamarin/". Is it because it should be at least 5.0 or > version rather than 4.2.3?

**Comment by berkus** [comment]
The Xamarin SDK does not generate your tokens, your token generator is obsolete. Which token generator do you use?

**Comment by AlfonChitoSalano** [comment]
> 
> 
> The Xamarin SDK does not generate your tokens, your token generator is obsolete. Which token generator do you use?

I've just updated the token generator with this one, just this now. I got one success, only one only, but then the next try rest same issue again.

![bb](https://user-images.githubusercontent.com/20876086/78350147-47b9d180-75d7-11ea-9cfa-46e44dd8c0f8.png)

**Comment by berkus** [comment]
What is in the new token? What is the new error?

**Comment by AlfonChitoSalano** [comment]
> 
> 
> What is in the new token? What is the new error?

So I got it success already. so the fix was to change script like above to "new ChatGrant". Then I change the code of the example in twilio xamarin to below which gets the token property only. This worked already with no error. So I think this could be closed.
 string chatToken = await _twilioChatHelper.GetTokenProvider().GetToken(IdentityEntry);
 string tokenData = JObject.Parse(chatToken)["token"].ToString();

**Comment by berkus** [comment]
Ok, great, glad you figured that out! 

Closing then. Feel free to open a new one if you have further questions.
