### ISSUE TITLE
android bindings use deprecated version 4.2.3

### ISSUE THREAD

**Issue by thisisthekap** [twilio/TwilioChatXamarinBindings#30]
The android bindings are using a old deprecated version of the sdk.

Are there plans to update it to the current production one?

**Comment by berkus** [comment]
Hi!

Yes, we will update Xamarin bindings to use the latest 3.0/5.0 versions of native SDKs asap.

**Comment by berkus** [comment]
I can't give you hard estimates, but it would be between 1 to 3 weeks from now, depending on other priorities.

**Comment by thisisthekap** [comment]
@berkus Is there any update concerning this issue?

As this one is key to out twilio integration, any progress would be very much appreciated.

**Comment by berkus** [comment]
Hi, yes, it's in progress, however some other things took higher priority at the moment. We will  release updated Xamarin bingings ASAP.

**Comment by thisisthekap** [comment]
@berkus As we depend on this issue to be able to use twilio in production: Can you already provide me any ETA on this?

**Comment by berkus** [comment]
I'll do my best to finish it this week.

**Comment by berkus** [comment]
Haven't forgotten about you - still fighting some Android obsoleted packages before I could release it.

**Comment by AhmedTaha0** [comment]
Any updates @berkus

**Comment by berkus** [comment]
Yep, it took me a LOT longer than I expected but I got it updated and now prepping to make a release. It will be followed up by another release immediately afterwards - bumping to new versions 5.1.1 and 3.1.1.
