### ISSUE TITLE
Xamarin.iOS Update to 0.7.0 fails

### ISSUE THREAD

**Issue by mrbelk** [twilio/TwilioChatXamarinBindings#34]
Trying to update this package in my Android and iOS projects and get this error when updating for iOS:

```
Checking compatibility for Com.Getkeepsafe.Relinker 1.3.1 with Xamarin.iOS,Version=v1.0 (win-x86).
Package Com.Getkeepsafe.Relinker 1.3.1 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Package Com.Getkeepsafe.Relinker 1.3.1 supports: monoandroid (MonoAndroid,Version=v0.0)
```

I can update to 0.7.0 for Android no problem.

**Comment by berkus** [comment]
Hi, thanks, this could be a mishap on our side, I will take a look soon.

**Comment by mrbelk** [comment]
OK. Thanks.

________________________
Matthew Belk
ph. 678-287-3315

**Comment by berkus** [comment]
Please try 0.7.2

**Comment by mrbelk** [comment]
Success. Thanks for getting on this so quickly.

**Comment by berkus** [comment]
👍
