### ISSUE TITLE
TVICameraCapturer Not found and i not able to set Source to Front camera [Question ].

### ISSUE THREAD

**Issue by pranavtiw** [twilio/TwilioChatXamarinBindings#37]
camera = new TVICameraCapturer(TVICameraCaptureSource.FrontCamera);
            
localVideoTrack = TVILocalVideoTrack.TrackWithCapturer(capturer:camera,enabled:true,constraints:null,name:null);

This is the way i have done it in previous version .

**Comment by berkus** [comment]
This is Chat bindings, it doesn't deal with Camera.

**Comment by pranavtiw** [comment]
Sorry  i wanted to create for Twilio video

**Comment by berkus** [comment]
No prob )
