### ISSUE TITLE
After updating to 0.7.X Getting Error XA4215

### ISSUE THREAD

**Issue by sauravchaudhary94** [twilio/TwilioChatXamarinBindings#38]
Till 0.6.0 It is working fine but while updating to 0.7 and above I am getting the below error:
 Error XA4215: The Java type `mono.com.getkeepsafe.relinker.ReLinker_LoadListenerImplementor` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.

**Comment by berkus** [comment]
1. How are you adding it to your project?

2. Do you have a manually added relinker dependency?

**Comment by sauravchaudhary94** [comment]
1. I am adding nuget package to the project and handled callback , As It is working till 0.6.0 version.
2. Yes I have added relinker for twilio video chat library Xbindings.Relinker.Droid(1.2.3).

**Comment by berkus** [comment]
2. Try removing it.

I suspect you are importing two incompatible relinker versions there.

**Comment by sauravchaudhary94** [comment]
If I remove It I will get error in Video Chat It seems.

**Comment by berkus** [comment]
1. Have you actually tried removing it?

2. Can you try adding exactly the same dependency for video chat as this project uses? Maybe if it's the same package it could resolve it to a single dependency instead of two incompatible ones.

**Comment by sauravchaudhary94** [comment]
1. After removing and updating video binding to 4.3.X It seems to be working from my end. But Once regression testing will be done I can be sure like Video is not breaking and It is working . 
But May I know why we didn't get this error till 0.6.0?

Thanks for your help :)

**Comment by berkus** [comment]
> But May I know why we didn't get this error till 0.6.0?

Sure, 0.6.0 did not use separate ReLinker dependency on android, it was built in, old and not updated. We switched to external dependency to make it easier to update and fix ReLinker issues if they come up.

As far as I know ReLinker folks claim their tool is not needed on modern Android API versions (API 23 and above), but given that there are very many vendors, who can do badly things that ReLinker tries to mitigate, it's still makes sense to keep it around. At least for a few more years (until we drop API 19 support).

**Comment by berkus** [comment]
Closing it, since all seems fine now.
