### ISSUE TITLE
PCL - Twilio.Chat.Xamarin.0.1.1 is not compatible with PCL

### ISSUE THREAD

**Issue by whitewolf33** [twilio/TwilioChatXamarinBindings#4]
Tried to install the Twilio.Chat.Xamarin nuget package v0.1.1 to a PCL project (profile 111), by creating a Blank App in VS Mac and found out that the package is not compatible.

Version of the package: 0.1.1

VS Mac Version: 7.3.3.12

Steps to Reproduce;

1. Open VS Mac 
2. File => New Solution
3. Select Blank App (with PCL)
4. In the PCL project, add nuget reference to Twilio.Chat.Xamarin

Details from the Package Manager below:

> Attempting to gather dependency information for package 'Twilio.Chat.Xamarin.0.1.1' with respect to project 'TwilioChatTest', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
> GET https://api.nuget.org/v3/registration3-gz-semver2/twilio.chat.xamarin/index.json
> OK https://api.nuget.org/v3/registration3-gz-semver2/twilio.chat.xamarin/index.json 294ms
> Total number of results gathered : 2
> Gathering dependency information took 297.25 ms
> Summary of time taken to gather dependencies per source :
> https://api.nuget.org/v3/index.json	-	296.75 ms
> Attempting to resolve dependencies for package 'Twilio.Chat.Xamarin.0.1.1' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'Twilio.Chat.Xamarin.0.1.1'
> Resolved actions to install package 'Twilio.Chat.Xamarin.0.1.1'
> Found package 'Twilio.Chat.Xamarin 0.1.1' in '/Users/XX/Desktop/TwilioChatTest/packages'.
> For adding package 'Twilio.Chat.Xamarin.0.1.1' to project 'TwilioChatTest' that targets 'portable45-net45+win8+wpa81'.
> Install failed. Rolling back...
> Package 'Twilio.Chat.Xamarin.0.1.1' does not exist in project 'TwilioChatTest'
> Executing nuget actions took 15.12 ms
> Could not install package 'Twilio.Chat.Xamarin 0.1.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by whitewolf33** [comment]
Hi @aleksandrsivanovs;

Is there any ETA on this fix? 

I am planning to build a chat sample with PCL and have a full chat conversation between 2 users by creating a channel.
 
Does the current native binding done for Twilio.Chat.Xamarin support this? Please let me know so I will be prepared what to expect.

Thanks.

**Comment by aleksandrsivanovs** [comment]
afaik, PCL requires win8 and wpa81 libraries and our current binding is wrapping Android library and iOS library (with different interfaces) - so, the answer is that we don't support PCL in this release.

and I can't comment on win8/win10/uwp readiness anytime soon :)

**Comment by aleksandrsivanovs** [comment]
I'll close this issue if you have nothing against it :)
