### ISSUE TITLE
iOS: Native linking failed errors

### ISSUE THREAD

**Issue by JoeDurand3** [twilio/TwilioChatXamarinBindings#40]
Trying to build iOS project including version 0.7.2 and getting these errors of this variety:

```
Native linking failed. Please review the build log and the user flags provided to gcc: -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/user/Library/Caches/Xamarin/mtbs/builds/AppName.iOS/9535dc2d0e7ea7a775654025ed7b5bd3/obj/iPhoneSimulator/Debug/Entitlements.xcent	AppName.iOS			

Native linking failed, undefined symbol: _TCHErrorMsgKey. This symbol was referenced by the managed member Twilio.Chat.iOS.Constants.ErrorMsgKey. Please verify that all the necessary frameworks have been referenced and native libraries linked.	AppName.iOS			

Native linking failed, undefined Objective-C class: TCHError. The symbol '_OBJC_CLASS_$_TCHError' could not be found in any of the libraries or frameworks linked with your application.	AppName.iOS		
```

Any suggestions?

edit: code format

**Comment by berkus** [comment]
Hi!

Did you install it through NuGet? Looks like some binary libraries are missing.

**Comment by JoeDurand3** [comment]
Hello!

I did install via NuGet. Would you suggest building from source instead?

Full error list, also attached:
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Native linking failed. Please review the build log and the user flags provided to gcc: -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/USERNAME/Library/Caches/Xamarin/mtbs/builds/APPNAME.iOS/9535dc2d0e7ea7a775654025ed7b5bd3/obj/iPhoneSimulator/Debug/Entitlements.xcent	APPNAME.iOS			
Error		warning: ignoring file /Users/USERNAME/Library/Caches/Xamarin/mtbs/builds/APPNAME.iOS/9535dc2d0e7ea7a775654025ed7b5bd3/obj/iPhoneSimulator/Debug/mtouch-cache/TwilioChatClient.framework/TwilioChatClient, missing required architecture i386 in file /Users/USERNAME/Library/Caches/Xamarin/mtbs/builds/APPNAME.iOS/9535dc2d0e7ea7a775654025ed7b5bd3/obj/iPhoneSimulator/Debug/mtouch-cache/TwilioChatClient.framework/TwilioChatClient (2 slices)	APPNAME.iOS			
Error		Native linking failed, undefined symbol: _TCHErrorMsgKey. This symbol was referenced by the managed member Twilio.Chat.iOS.Constants.ErrorMsgKey. Please verify that all the necessary frameworks have been referenced and native libraries linked.	APPNAME.iOS			
Error		Native linking failed, undefined symbol: _TCHErrorGeneric. This symbol was referenced by the managed member Twilio.Chat.iOS.Constants.ErrorGeneric. Please verify that all the necessary frameworks have been referenced and native libraries linked.	APPNAME.iOS			
Error		Native linking failed, undefined symbol: _TCHErrorDomain. This symbol was referenced by the managed member Twilio.Chat.iOS.Constants.ErrorDomain. Please verify that all the necessary frameworks have been referenced and native libraries linked.	APPNAME.iOS			
Error		Native linking failed, undefined symbol: _TCHChannelOptionUniqueName. This symbol was referenced by the managed member Twilio.Chat.iOS.Constants.ChannelOptionUniqueName. Please verify that all the necessary frameworks have been referenced and native libraries linked.	APPNAME.iOS			
Error		Native linking failed, undefined symbol: _TCHChannelOptionType. This symbol was referenced by the managed member Twilio.Chat.iOS.Constants.ChannelOptionType. Please verify that all the necessary frameworks have been referenced and native libraries linked.	APPNAME.iOS			
Error		Native linking failed, undefined symbol: _TCHChannelOptionFriendlyName. This symbol was referenced by the managed member Twilio.Chat.iOS.Constants.ChannelOptionFriendlyName. Please verify that all the necessary frameworks have been referenced and native libraries linked.	APPNAME.iOS			
Error		Native linking failed, undefined symbol: _TCHChannelOptionAttributes. This symbol was referenced by the managed member Twilio.Chat.iOS.Constants.ChannelOptionAttributes. Please verify that all the necessary frameworks have been referenced and native libraries linked.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TwilioChatClientProperties. The symbol '_OBJC_CLASS_$_TwilioChatClientProperties' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TwilioChatClient. The symbol '_OBJC_CLASS_$_TwilioChatClient' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHUsers. The symbol '_OBJC_CLASS_$_TCHUsers' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHUserDescriptorPaginator. The symbol '_OBJC_CLASS_$_TCHUserDescriptorPaginator' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHUserDescriptor. The symbol '_OBJC_CLASS_$_TCHUserDescriptor' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHUser. The symbol '_OBJC_CLASS_$_TCHUser' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHResult. The symbol '_OBJC_CLASS_$_TCHResult' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHMessages. The symbol '_OBJC_CLASS_$_TCHMessages' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHMessageOptions. The symbol '_OBJC_CLASS_$_TCHMessageOptions' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHMessage. The symbol '_OBJC_CLASS_$_TCHMessage' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHMembers. The symbol '_OBJC_CLASS_$_TCHMembers' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHMemberPaginator. The symbol '_OBJC_CLASS_$_TCHMemberPaginator' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHMember. The symbol '_OBJC_CLASS_$_TCHMember' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHJsonAttributes. The symbol '_OBJC_CLASS_$_TCHJsonAttributes' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHError. The symbol '_OBJC_CLASS_$_TCHError' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHChannels. The symbol '_OBJC_CLASS_$_TCHChannels' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHChannelDescriptorPaginator. The symbol '_OBJC_CLASS_$_TCHChannelDescriptorPaginator' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHChannelDescriptor. The symbol '_OBJC_CLASS_$_TCHChannelDescriptor' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		Native linking failed, undefined Objective-C class: TCHChannel. The symbol '_OBJC_CLASS_$_TCHChannel' could not be found in any of the libraries or frameworks linked with your application.	APPNAME.iOS			
Error		linker command failed with exit code 1 (use -v to see invocation)	APPNAME.iOS		
`

**Comment by berkus** [comment]
No, I don't think building from source is intended use of this package, I recommend installing from NuGet, of course.

What architecture are you building?

**Comment by berkus** [comment]
> missing required architecture i386 in file /Users/USERNAME/Library/Caches/Xamarin/mtbs/builds/

Ah, I see, this is the problem - x86 is no longer supported.

**Comment by JoeDurand3** [comment]
That was it! Thank you very much!

I went to iOS project properties > iOS Build > Supported Architectures and changed from "i386 + x86_64" to "x86_64"
